In [2]:
import pandas as pd
import numpy as np

In [ ]:
categories = [
    'alt.atheism',
    'talk.religion.misc',
    'comp.graphics',
    'sci.space'
]

df_test = pd.read_csv("../data/raw/20_newsgroups_test.csv")
df_test = df_test[df_test['label_text'].isin(categories)]
df_test

,text,label,label_text
2,"\nIn a word, yes.\n",0,alt.atheism
4,\nI've just spent two solid months arguing tha...,19,talk.religion.misc
9,": \n: well, i have lots of experience with sc...",1,comp.graphics
14,\nProbably because it IS rape.\n\n\nSo nothing...,0,alt.atheism
17,"Hello,\ni'm interested in those devices too.\n...",1,comp.graphics
...,...,...,...
7488,"\n\namen.. I too have learned by example, spec...",1,comp.graphics
7492,"\n: I agree, I had a hard feeling not believin...",0,alt.atheism
7496,"\n\nYes a flotation tank, combined with florid...",14,sci.space
7505,Archive-name: atheism/overview\nAlt-atheism-ar...,0,alt.atheism
7527,"\n Henry, if I read you correctly, you may b...",14,sci.space

In [15]:
df_test.to_csv("../data/processed/20_newsgroups_3_categories_test.csv", index=False)

In [10]:
df_train = pd.read_csv("../data/raw/20_newsgroups_train.csv")
df_train = df_train[df_train['label_text'].isin(categories)]
df_train

,text,label,label_text
3,\nDo you have Weitek's address/phone number? ...,1,comp.graphics
4,"From article <C5owCB.n3p@world.std.com>, by to...",14,sci.space
11,"\nYep, that's pretty much it. I'm not a Jew bu...",19,talk.religion.misc
13,"\n {Description of ""External Tank"" option fo...",14,sci.space
15,\nDon't be so sure. Look what happened to Jap...,0,alt.atheism
...,...,...,...
11276,"A new alternative to Scouting for those ""unacc...",0,alt.atheism
11286,\n\n\n\n\nThe HGA isn't all that reflective in...,14,sci.space
11289,I have a Diamond Speedstar 24X board that I wa...,1,comp.graphics
11304,NaN,19,talk.religion.misc
11312,\nWouldn't this require a hyper-sphere. In 3-...,1,comp.graphics

In [16]:
df_train.to_csv("../data/processed/20_newsgroups_3_categories_train.csv", index=False)

In [3]:
import kagglehub
crawford_20_newsgroups_path = kagglehub.dataset_download('crawford/20-newsgroups')

print('Data source import complete.')
from sklearn.datasets import fetch_20newsgroups

Data source import complete.

In [49]:
categories = ['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

data_train = fetch_20newsgroups(
    subset='train',
    categories=categories,
    shuffle=True,
    random_state=42
)
data_test = fetch_20newsgroups(
    subset='test',
    categories=categories,
    shuffle=True,
    random_state=42
)
df_sklearn_train = pd.DataFrame({'text': data_train.data, 'label': data_train.target})
df_sklearn_train['label_text'] = df_sklearn_train['label'].apply(lambda x: data_train.target_names[x])
df_sklearn_train.to_csv("../data/raw/20_newsgroups_train.csv", index=False)
df_sklearn_test = pd.DataFrame({'text': data_test.data, 'label': data_test.target})
df_sklearn_test['label_text'] = df_sklearn_test['label'].apply(lambda x: data_test.target_names[x])
df_sklearn_test.to_csv("../data/raw/20_newsgroups_test.csv", index=False)
df_sklearn_test

In [ ]:
df_sklearn_train

In [37]:
df_sklearn_test["label_text"].unique().tolist()

['sci.space', 'comp.graphics', 'alt.atheism', 'talk.religion.misc']

In [4]:
categories = [
    'alt.atheism',
    'talk.religion.misc',
    'comp.graphics',
    'sci.space'
]
data_train = fetch_20newsgroups(
    subset='train',
    categories=categories,
    shuffle=True,
    random_state=42
)
data_test = fetch_20newsgroups(
    subset='test',
    categories=categories,
    shuffle=True,
    random_state=42
)
df_sklearn_train = pd.DataFrame({'text': data_train.data, 'label': data_train.target})
df_sklearn_train['label_text'] = df_sklearn_train['label'].apply(lambda x: data_train.target_names[x])
df_sklearn_train.to_csv("../data/raw/20_newsgroups_3_categories_train.csv", index=False)

df_sklearn_test = pd.DataFrame({'text': data_test.data, 'label': data_test.target})
df_sklearn_test['label_text'] = df_sklearn_test['label'].apply(lambda x: data_test.target_names[x])
df_sklearn_test.to_csv("../data/raw/20_newsgroups_3_categories_test.csv", index=False)
df_sklearn_test

,text,label,label_text
0,From: prb@access.digex.net (Pat)\nSubject: Re:...,2,sci.space
1,From: ing1023@ee.up.ac.za (ING1023)\nSubject: ...,1,comp.graphics
2,From: Zheng Wang <zw10+@andrew.cmu.edu>\nSubje...,1,comp.graphics
3,From: edimg@willard.atl.ga.us (Ed Pimentel)\nS...,1,comp.graphics
4,From: stern@brahms.udel.edu (Garland Stern)\nS...,1,comp.graphics
...,...,...,...
1348,From: egret@wet.UUCP (thomas helke)\nSubject: ...,1,comp.graphics
1349,From: neff@iaiowa.physics.uiowa.edu (John S. N...,2,sci.space
1350,From: tbrent@ecn.purdue.edu (Timothy J Brent)\...,3,talk.religion.misc
1351,From: gotsman@csa.technion.ac.il (Craig Gotsma...,1,comp.graphics
1352,From: ph14@cunixb.cc.columbia.edu (Pei Hsieh)\...,1,comp.graphics

In [5]:
df_sklearn_train

,text,label,label_text
0,From: rych@festival.ed.ac.uk (R Hawkes)\nSubje...,1,comp.graphics
1,Subject: Re: Biblical Backing of Koresh's 3-02...,3,talk.religion.misc
2,From: Mark.Perew@p201.f208.n103.z1.fidonet.org...,2,sci.space
3,From: dpw@sei.cmu.edu (David Wood)\nSubject: R...,0,alt.atheism
4,From: prb@access.digex.com (Pat)\nSubject: Con...,2,sci.space
...,...,...,...
2029,From: arthurc@sfsuvax1.sfsu.edu (Arthur Chandl...,2,sci.space
2030,From: schaefer@sal-sun121.usc.edu (Peter Schae...,2,sci.space
2031,From: jamie@genesis.MCS.COM (James R Groves)\n...,1,comp.graphics
2032,From: halat@pooh.bears (Jim Halat)\nSubject: I...,0,alt.atheism
2033,From: kai_h@postoffice.utas.edu.au (Kai Howell...,1,comp.graphics